[phases.setup]
nixPkgs = ["chromium", "glib", "nss", "atk", "cups", "libdrm", "libxkbcommon", "libxcomposite", "libxdamage", "libxrandr", "libgbm", "pango", "cairo"]

[start]
cmd = "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true node index.js"
